import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'title': 'Card Scanner',
          'login': 'Login',
          'login_anonymous': 'Login anonymous',
          'sign_up': ' Sign up',
          'logout': 'Logout',
          'enter_email': 'Enter email',
          'enter_password': 'Enter password',
          'password': 'Password',
          'password_not_match': 'Password not match',
          'email_invalid': 'Email invalid!',
          'pwd_invalid': 'Password invalid!',
          'have_not_acc': 'New user?',
          'forgot_pwd': 'Forgot password?',
          'reset_password': 'Reset password',
          'connecting_with': '----- Or connecting with -----',
          'message': 'Message',
          'find_friend': 'Find friend',
          'setting': 'Setting',
          'sound_and_notification': 'Sound and notification',
          'notification': 'Notification',
          'sound': 'Sound',
          'preview_notification': 'Preview notification',
          'notification_vibrate': 'Vibrate',
          'notification_led': 'Notification LED',
          'your_profile': 'Your profile',
          'language': 'Language',
        },
        'vi_VN': {
          'title': 'Quét Card',
          'login': 'Đăng nhập',
          'login_anonymous': 'Đăng nhập ẩn danh',
          'sign_up': ' Đăng ký',
          'logout': 'Đăng xuất',
          'enter_email': 'Nhập email',
          'enter_password': 'Nhập mật khẩu',
          'password': 'Mật khẩu',
          'password_not_match': 'Mật khẩu không khớp',
          'email_invalid': 'Email sai!',
          'pwd_invalid': 'Password sai!',
          'have_not_acc': 'Người mới',
          'forgot_pwd': 'Quên mật khẩu?',
          'reset_password': 'Khôi phục mật khẩu',
          'connecting_with': '----- Hoặc liên kết tài khoản -----',
          'message': 'Tin nhắn',
          'find_friend': 'Tìm bạn',
          'setting': 'Cài đặt',
          'sound_and_notification': 'Âm thanh và thông báo',
          'notification': 'Thông báo',
          'sound': 'Âm thanh',
          'preview_notification': 'Xem trước thông báo',
          'notification_vibrate': 'Báo rung',
          'notification_led': 'Đèn báo',
          'your_profile': 'Thông tin cá nhân',
          'language': 'Ngôn ngữ',
        }
      };
}
